language: python
sudo: required
install:
  - pip3 install --upgrade pip
  - pip3 install requests
  - pip3 install mkdocs
  - pip3 install mkdocs-material
script:
  - cd files/zh-CN && mkdocs build
  - cd ../en-US && mkdocs build
  - python3 ./deploy.py