site_name: 'MDx Document'
site_description: 'English doc for theme MDx.'
site_author: 'Axton'
site_url: 'https://doc.flyhigher.top/mdx/en-US/'

# Repository
repo_name: 'yrccondor/mdx'
repo_url: 'https://github.com/yrccondor/mdx'
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 AxtonYao'

# Configuration
theme:
  name: 'material'
  language: 'en'
  logo: 'img/logo.png'
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  include_search_page: false
  search_index_only: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/yrccondor/mdx'
    - type: 'globe'
      link: 'https://mdx.flyhigher.top/'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - MDx Docs: index.md
  - Before Start: before-start.md
  - Install, Upgrade & Uninstall: install.md
  - Configuration:
    - Personalization: config/personalization.md
    - Styles: config/styles.md
    - Config Menu: config/menu.md
    - Image Of the Post: config/post-img.md
    - Friend Links: config/links.md
    - Widgets: config/tools.md
    - Emotions in Comments: config/emoji-in-comment.md
    - ImgBox: config/imgbox.md
    - Real Time Search: config/real-time-search.md
    - Config Install Method: config/install-info.md
    - Multi-Language: config/multi-language.md
    - Page Templates: config/page-template.md
  - Shortcodes:
    - Table: shortcodes/table.md
    - Folder: shortcodes/folder.md
    - Warning: shortcodes/warning.md
    - Progress Bar: shortcodes/progress.md
    - Github Info Card: shortcodes/github-info-card.md
    - Post Info Card: shortcodes/post-info-card.md
  - Technical info:
    - Common PHP Errors: tech/php-errors.md
    - Frameworks & Libraries: tech/frameworks.md
  - FAQ: faq.md
  - Privacy Policy: privacy.md
  - Roadmap: roadmap.md
  - Help Us: help-us.md
  - Languages:
    - 简体中文: 'https://doc.flyhigher.top/mdx/zh-CN/'
    - English: 'https://doc.flyhigher.top/mdx/en-US/'
    - Türkçe: 'https://doc.flyhigher.top/mdx/tr-TR/'